### PR TITLE
Knowledge Base Web deployment

### PR DESCRIPTION
**Pull request by yonglbl**
Knowledge Base Web Init files

need place this [.env](https://drive.google.com/file/d/1H4Mxbo6sc3ZDC4OthUwUdDcW9LN-w3Qz/view?usp=drive_link) file under /backend

### CODE REVIEW

**Comment by dsclassen** [comment]
seems fine to me...

**Review by dsclassen — APPROVED** [review]
go for it

**Comment by yonglbl** [comment]
@dsclassen can deploy this to server?

**Comment by dsclassen** [comment]
I don't have permission to merge. For now I will just work with the `init-files` branch, and once things settle down we can work on proper workflows etc.

**Pull request merged**
